spring.application.name=RabbitMq
server.port=8083
spring.docker.compose.enabled=false

spring.datasource.url=jdbc:h2:file:./data/oficina_mecanica;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:oficina.sql

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin

app.rabbitmq.exchange=oficina.exchange
app.rabbitmq.queue=oficina.ordens-servico.criadas
app.rabbitmq.routing-key=oficina.ordem-servico.criada

app.python.command=python
app.python.validator-script=src/main/python/validar_mensagem.py
