CREATE TABLE IF NOT EXISTS ordens_servico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_cliente VARCHAR(80) NOT NULL,
    modelo_carro VARCHAR(80) NOT NULL,
    placa VARCHAR(8) NOT NULL,
    descricao_problema VARCHAR(300) NOT NULL,
    mecanico_responsavel VARCHAR(80) NOT NULL,
    valor_estimado NUMERIC(10, 2),
    status VARCHAR(30) NOT NULL CHECK (status IN ('RECEBIDA', 'EM_DIAGNOSTICO', 'FINALIZADA')),
    criada_em TIMESTAMP NOT NULL
);

MERGE INTO ordens_servico (
    id,
    nome_cliente,
    modelo_carro,
    placa,
    descricao_problema,
    mecanico_responsavel,
    valor_estimado,
    status,
    criada_em
) KEY (id) VALUES
(
    -1,
    'Marina Costa',
    'Chevrolet Onix 2020',
    'BRA2E19',
    'Motor falhando ao acelerar',
    'Carlos',
    380.00,
    'RECEBIDA',
    CURRENT_TIMESTAMP
),
(
    -2,
    'Joao Pereira',
    'Volkswagen Gol 2015',
    'ABC1D23',
    'Freio rangendo e pedal baixo',
    'Toretto',
    520.00,
    'EM_DIAGNOSTICO',
    CURRENT_TIMESTAMP
);
